### ISSUE TITLE
`mdx-deck build` errors with "Cannot read property 'step' of null"

### ISSUE THREAD

**Issue by spicydonuts** [pomber/code-surfer#8] opened 2018-08-27 20:17 UTC
It seems `mdx-deck build` doesn't work if I use `CodeSurfer` (regardless of how `raw-loader` is used).. I get this:

```
[mdx-deck] building
[mdx-deck] rendering static html
Missing HeadProvider
[err] TypeError: Cannot read property 'step' of null
    at _class2.render (./node_modules/mdx-deck-code-surfer/dist/deck-code-surfer.js:93:30)
    at processChild (./node_modules/react-dom/cjs/react-dom-server.node.development.js:2207:18)
    at resolve (./node_modules/react-dom/cjs/react-dom-server.node.development.js:2064:5)
    at ReactDOMServerRenderer.render (./node_modules/react-dom/cjs/react-dom-server.node.development.js:2383:22)
    at ReactDOMServerRenderer.read (./node_modules/react-dom/cjs/react-dom-server.node.development.js:2357:19)
    at renderToString (./node_modules/react-dom/cjs/react-dom-server.node.development.js:2729:25)
    at renderHTML (./node_modules/mdx-deck/lib/html.js:57:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by jxnblk** [comment] 2018-08-27 23:39
This *should* be fixed in the latest release, but please feel free to reopen the issue on mdx-deck if it's still happening

**Comment by pomber** [comment] 2018-08-27 23:44
Just tested it with mdx-deck v1.6.9, `Notes` and `Appear` work, but it still fails with `CodeSurfer`. The error is the same as before.

**Comment by jxnblk** [comment] 2018-08-28 03:04
Ah yeah... 😬  I think the root of the issue is with React context being a singleton, but code-surfer is not getting the same context in the mdx-deck `build` step.

The changes in jxnblk/mdx-deck#144 should hopefully help with that by exposing a public `withDeck` HOC in the API. I.e. if you use `import { withDeck } from 'mdx-deck'` with this new API, then it should be getting the same React context.

Definitely wanna make sure that code-surfer works well with mdx-deck and would love to get your thoughts on the proposed API changes

**Comment by trevordmiller** [comment] 2018-09-01 18:29
Looking forward to the release of this one so I can build + host my presentations :) Thanks for all the great work!

**Comment by spicydonuts** [comment] 2018-09-03 16:53
Not sure if this is related, but I updated both libraries and am getting `TypeError: notes is not a function` whenever I put a note in CodeSurfer somewhere.

Coming from this function in `dist/deck-code-surfer.js`:
```js
var Notes = function Notes(_ref) {
  var notes = _ref.notes;
  return typeof notes === "string" ? _react2.default.createElement("p", { style: { height: "50px" } }, notes || "\xA0") : notes();
};
```

Versions:
- mdx-deck: 1.7.1
- mdx-deck-code-surfer: 0.4.0

React stack:
```
The above error occurred in the <Notes> component:
    in Notes (created by InnerCodeSurfer)
    in div (created by InnerCodeSurfer)
    in div (created by InnerCodeSurfer)
    in InnerCodeSurfer (created by WithTheme(InnerCodeSurfer))
    in WithTheme(InnerCodeSurfer)
    in Unknown
    in Unknown
    in div (created by MDXTag)
    in MDXTag
    in Unknown
    in Unknown (created by SlideDeck)
    in div (created by styled.div)
    in styled.div (created by Slide)
    in Slide (created by SlideDeck)
    in div (created by styled.div)
    in styled.div (created by Carousel)
    in div (created by styled.div)
    in styled.div (created by Carousel)
    in Carousel (created by SlideDeck)
    in div (created by styled.div)
    in styled.div (created by SlideDeck)
    in div (created by Swipeable)
    in Swipeable (created by SlideDeck)
    in Provider (created by SlideDeck)
    in MDXProvider (created by SlideDeck)
    in ThemeProvider (created by SlideDeck)
    in HeadProvider (created by SlideDeck)
    in SlideDeck (created by App)
    in App
```

**Comment by spicydonuts** [comment] 2018-09-03 16:58
If I give either every step (including step 0) a note or nothing a note, it works. Mixing causes the error.

**Comment by pomber** [comment] 2018-09-03 17:30
can you post the the code of the slide that's failing? also is this when using "mdx-deck build" or always?

**Comment by pomber** [comment] 2018-09-03 19:11
@spicydonuts the Notes bug should be fixed in mdx-deck-code-surfer v0.4.1

@trevordmiller I'm not sure how to fix `mdx-deck build` yet, as a workaround you can use `mdx-deck build --no-html your.mdx`

**Comment by spicydonuts** [comment] 2018-09-08 21:45
After updates I get this error instead:

```
[err] TypeError: Cannot read property 'update' of null
    at new InnerCodeSurfer (node_modules/mdx-deck-code-surfer/dist/deck-code-surfer.js:60:30)
    ...
```

`--no-html` still works without error

**Comment by jxnblk** [comment] 2018-09-08 21:54
I haven't really dug into this yet, but I suspect it might be related to mdx-deck's use of webpack-node-externals here: https://github.com/jxnblk/mdx-deck/blob/master/lib/html.js#L34-L38 – if anyone wants to test out a different setup there

**Comment by Leko** [comment] 2018-09-17 17:07
@jxnblk Hi.

> it might be related to mdx-deck's use of webpack-node-externals

Maybe you're right.
I changed `node_modules/mdx-deck/lib/html.js` as here:

```diff
   config.externals = [
     nodeExternals({
       whitelist: [
         'mdx-deck',
         'mdx-deck/themes',
+        'mdx-deck/layouts',
+        'mdx-deck-code-surfer'
       ]
     })
   ]
```

It works as expected but I didn't understand why it worked.

**Comment by ledicjp** [comment] 2018-10-03 18:38
@Leko your suggestion worked for me, thank you!

**Comment by faogustavo** [comment] 2018-10-17 10:45
Here, I also had to update _the deck-code-surfer.js_ file.
Now its like this (Starting at 127):

```
      var current = stepsWithNotes[stepIndex >= stepsWithNotes.length ? 0 : stepIndex];
      var currentStep = current && current.step;
      var currentTitle = current && current.title || title;
      var currentNotes = current && current.notes;
      var anyNotes = stepsWithNotes.some(function (s) {
        return s.notes;
      });
```

**Comment by sibelius** [comment] 2019-01-27 17:32
I've got this error

```jsx
TypeError: Cannot read property 'update' of null
    at new InnerCodeSurfer (/Users/sibelius/Dev/app/slides/functional-types-abstraction/node_modules/mdx-deck-code-surfer/dist/deck-code-surfer.js:93:30)
    at processChild (/Users/sibelius/Dev/app/slides/functional-types-abstraction/node_modules/react-dom/cjs/react-dom-server.node.development.js:2750:14)
    at resolve (/Users/sibelius/Dev/app/slides/functional-types-abstraction/node_modules/react-dom/cjs/react-dom-server.node.development.js:2716:5)
    at ReactDOMServerRenderer.render (/Users/sibelius/Dev/app/slides/functional-types-abstraction/node_modules/react-dom/cjs/react-dom-server.node.development.js:3100:22)
    at ReactDOMServerRenderer.read (/Users/sibelius/Dev/app/slides/functional-types-abstraction/node_modules/react-dom/cjs/react-dom-server.node.development.js:3059:29)
    at renderToString (/Users/sibelius/Dev/app/slides/functional-types-abstraction/node_modules/react-dom/cjs/react-dom-server.node.development.js:3526:27)
    at renderHTML (/Users/sibelius/Dev/app/slides/functional-types-abstraction/node_modules/mdx-deck/lib/html.js:65:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

You can reproduce running `yarn build` on this presentation https://github.com/sibelius/functional-types-abstractions

**Comment by raisiqueira** [comment] 2019-02-01 02:54
@sibelius same problem here... I run the build with `--no-html`, but don't work too.

**Comment by Athul-CA** [comment] 2019-02-02 14:54
> @jxnblk Hi.
> 
> > it might be related to mdx-deck's use of webpack-node-externals
> 
> Maybe you're right.
> I changed `node_modules/mdx-deck/lib/html.js` as here:
> 
> ```diff
>    config.externals = [
>      nodeExternals({
>        whitelist: [
>          'mdx-deck',
>          'mdx-deck/themes',
> -        'mdx-deck/layouts'
> +        'mdx-deck/layouts',
> +        'mdx-deck-code-surfer'
>        ]
>      })
>    ]
> ```
> 
> It works as expected but I didn't understand why it worked.

This actually Worked for me.Thanks @Leko

**Comment by sibelius** [comment] 2019-02-10 03:05
fixed here https://github.com/jxnblk/mdx-deck/pull/255

to fix mdx-code-surfer we gonna need a custom webpack config like this one:

const nodeExternals = require('webpack-node-externals');

webpack.config.js
```jsx
module.exports = {
  externals: [
     nodeExternals({
       whitelist: [
         'mdx-deck',
         'mdx-deck/themes',
          'mdx-deck/layouts',
          'mdx-deck-code-surfer'
       ]
     })
   ],
};
```

**Comment by pomber** [comment] 2019-12-10 15:28
Fixed in v3

**Closed by pomber** 2019-12-10 15:28 UTC
