### ISSUE TITLE
Code Surfer v3 RC

### ISSUE THREAD

**Issue by pomber** [pomber/code-surfer#70] opened 2019-10-02 03:57 UTC
Code Surfer v3 is almost done. 

If anyone wants to help me test it: create a new deck with `npm init code-surfer-deck my-deck`, work on your deck, and let me know if you have any problem.

### [Here are the docs](https://github.com/pomber/code-surfer/blob/code-surfer-v2/readme.md).

Improvements to the docs are also welcome.

**Comment by mplis** [comment] 2019-10-09 13:26
Wow this version is soooo good. The transitions and animations are perfect and the `CodeSurferColumns` component is extremely useful for comparing code.

**Comment by pomber** [comment] 2019-10-09 15:54
Thanks @mplis :pray:   
And thanks a lot for your contribution in Open Collective!

**Comment by danielgwilson** [comment] 2019-10-10 04:50
Seems to function beautifully—nice work!

**Comment by danielgwilson** [comment] 2019-10-10 07:01
FYI I'm getting fairly frequent crashes when using 250+ line code blocks (imported).

Will dig in more later, running mdx-deck as a child process so I can't really see the logs

```sh
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
  at Socket.onChildStdout (child_process.js:348:14)
  at Socket.emit (events.js:189:13)
  at addChunk (_stream_readable.js:284:12)
  at readableAddChunk (_stream_readable.js:261:13)
  at Socket.Readable.push (_stream_readable.js:220:10)
  at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
```

**Comment by felipeleusin** [comment] 2019-10-22 13:26
Just wanted to say thanks for all this work! Been playing around with it for a presentation and it's amazing right now!

**Comment by bcbrian** [comment] 2019-11-05 03:30
Shameless plug for my twitch stream, codequests, we used in the stream and everyone thought it was sick! Link to vid coming soon!

**Comment by ashrafhasson** [comment] 2019-11-10 16:03
Thanks for the awesome work!
I'm getting the following error when specifying a few languages:

> Oops, there's a problem
> Error: Missing syntax highlighting for language "elixir"
> 

I see that react-syntax-highlighter 11.0.2 is installed and that should have support for elixir, not sure if there's a dependency issue here?

**Comment by pomber** [comment] 2019-11-10 16:35
@ashrafhasson see here how to add languages: https://github.com/pomber/code-surfer/blob/code-surfer-v2/readme.md#languages

I'm going to add more info to the error to make it easier to fix.

**Comment by ashrafhasson** [comment] 2019-11-10 16:48
@pomber thanks for the quick response .. I should have read that more carefully, assumed all prismjs languages were loaded out of the box .. sorry

Once more, thanks for the awesome work!

**Comment by jeffscottward** [comment] 2019-11-14 17:33
> FYI I'm getting fairly frequent crashes when using 250+ line code blocks (imported).
> 
> Will dig in more later, running mdx-deck as a child process so I can't really see the logs
> 
> ```shell
> RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
>   at Socket.onChildStdout (child_process.js:348:14)
>   at Socket.emit (events.js:189:13)
>   at addChunk (_stream_readable.js:284:12)
>   at readableAddChunk (_stream_readable.js:261:13)
>   at Socket.Readable.push (_stream_readable.js:220:10)
>   at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
> ```
> 
> Occurs after making several edits with hot reload

Seems like a limitation of Socket.io.
Dunno if anything could be done in this library. Saving frequently probably builds up that buffer and gets overloaded. Socket.io is well battle tested so I imagine they have their reasons for such a limitation.

250 lines also sounds quite big, probably should break that up.

@pomber I think any further changes would be in the hotfix tier. I would vote ship it :)

**Comment by pomber** [comment] 2019-11-15 15:30
> @pomber I think any further changes would be in the hotfix tier. I would vote ship it :)

I'll try to publish the new version next week!

**Comment by JackWink** [comment] 2019-11-15 18:48
@pomber Noticed a bug -- when using an imported language (ex: protobuf) it seems to parse and highlight correctly as part of a `<CodeSurfer>` element, but not within in a `<Step>` element.

**Comment by trevordmiller** [comment] 2019-11-19 23:42
Would love to see support for raw-loader again. I like having my source files be the single source of truth for what I code surf through - so that I can run linting / formatting / tests etc. on them and know that the code I am stepping through is working.

**Comment by trevordmiller** [comment] 2019-11-20 00:08
It seems that perhaps the children of `<CodeSurfer>` are not valid MDX? For example, the MDX below breaks with syntax highlighting and prettier auto formatting.

`deck.mdx`

```mdx
import { CodeSurfer } from "code-surfer";
import Wrapper from "./components/Wrapper";
import SomeComponent from "./components/SomeComponent"; 

# Some title

---

<SomeComponent />

---

<CodeSurfer>

\`\`\`js
console.log(1);
\`\`\`

\`\`\`js
console.log(1);
console.log(2);
\`\`\`

</CodeSurfer>

---

# The end
```

```sh
npx prettier deck.mdx
```

```error
SyntaxError: Unexpected closing tag "CodeSurfer". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags
```

**Comment by pomber** [comment] 2019-11-22 02:27
> @pomber Noticed a bug -- when using an imported language (ex: protobuf) it seems to parse and highlight correctly as part of a `<CodeSurfer>` element, but not within in a `<Step>` element.

@JackWink could you share the mdx for the bug?

**Comment by pomber** [comment] 2019-11-22 02:29
> Would love to see support for raw-loader again. I like having my source files be the single source of truth for what I code surf through - so that I can run linting / formatting / tests etc. on them and know that the code I am stepping through is working.

@trevordmiller have you tried [the `file` prop](https://github.com/pomber/code-surfer/blob/code-surfer-v2/readme.md#import-code)?

**Comment by jebeck** [comment] 2019-11-22 09:44
I've seen the same problem as @trevordmiller even with the file prop:

```
<CodeSurfer theme={nightOwl}>

  ```js file=./code/transferable-objects.js title="transferable objects"
  ```

</CodeSurfer>
```

Yields this in Prettier (via VS Code, doesn't matter if I have eslint-prettier turned off or on, result is the same):

```
Unexpected closing tag "CodeSurfer". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:1)
```

**Comment by pomber** [comment] 2019-11-23 14:50
@trevordmiller @jebeck I'm not sure I'm understanding the issue. 

Does it happen everytime? For example, does the deck from `npm init code-surfer-deck my-deck` work for you?

**Comment by trevordmiller** [comment] 2019-11-23 21:39
@pomber I get the issue with `npm init code-surfer-deck my-deck` and then `npx prettier deck.mdx`. To be fair, it isn't an error with this repo. But it does expose that the new API (`<CodeSurfer>{newline}{markdown code}{newline}</CodeSurfer>`) may not be valid MDX? Either that or Prettier parsing needs to be updated to support this type of syntax if it is valid. My editor doesn't recognize the syntax either so my gut says it is most likely not valid MDX.

**Comment by pomber** [comment] 2019-11-23 21:55
I see. Here is [the error in prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAwhAJnAygVwCcAzOQgPgB0pqADegKwGdrIomIAbOAOk4gDmACgCMASgDcdetWqoA9JhwESZciAA0ICAAcYAS2hNkoAIaFCEAO4AFcwmMpTANwj6smkACNCpsAGs4GFwdP30oAWQYQnw4LQALGABbTgB1eP14JlCwPAdM-WdMgE9kcCZjLXCmMhgbXwEk02RiU04arWYADwAhXwCg3FMkuAAZcLgWto6QbtxwgW4ARXwIeCn2uJBQwhrCMqSsLs8dQnCYVPcYeOQADgAGLVOIGtTfHTLTuD3nSa0AR1W8HqukcIFMTAAtFA4HAcB4tIQ4ID9Ej6qZGs0kK1Nloakl9FEYlsmAtlkDJtjplsYKYvJcsNdkAAmLTRUz6TgLTBJJplKDQP4gfA1AAqdMcOJqAF9pUA).

I belive it should be valid MDX. At least it's valid markdown according to the [commonsmark spec](https://spec.commonmark.org/0.29/#example-136).

Maybe open an issue for Prettier? I think it was working before, I always used prettier for my code surfer decks.

**Comment by trevordmiller** [comment] 2019-11-23 22:06
@pomber I've opened an issue with Prettier:
https://github.com/prettier/prettier/issues/7041

It sounds like it is unrelated to this repo so it shouldn't hold back the release (assuming the new API is valid MDX syntax).

**Comment by mxstbr** [comment] 2019-11-29 13:17
Whenever I run `npm start` and change the `deck.mdx` file (no matter what the change is) I run into this error:

```
 ERROR 

Cannot read property 'internal' of null



  TypeError: Cannot read property 'internal' of null
  
  - gen-mdx.js:48 payloadCacheKey
    [hooks]/[gatsby-plugin-mdx]/utils/gen-mdx.js:48:46
  
  - gen-mdx.js:51 genMDX
    [hooks]/[gatsby-plugin-mdx]/utils/gen-mdx.js:51:43
  
  - source-nodes.js:108 processMDX
    [hooks]/[gatsby-plugin-mdx]/gatsby/source-nodes.js:108:5
  
  - source-nodes.js:158 resolve
    [hooks]/[gatsby-plugin-mdx]/gatsby/source-nodes.js:158:35
  
  - gatsby-node.js:40 
    [hooks]/[gatsby-theme-mdx-deck]/gatsby-node.js:40:24
  
  - gatsby-node.js:47 resolveTitle
    [hooks]/[gatsby-theme-mdx-deck]/gatsby-node.js:47:60
  

not finished createPages - 0.075s


———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
3 pages                                                           In Progress                                                          mdx-deck
Error: Command failed with exit code 1 (EPERM): gatsby develop --host localhost --port 8000 --open
    at makeError (/Users/mxstbr/projects/mxstbr/modern-react-workshop/hooks/node_modules/mdx-deck/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/mxstbr/projects/mxstbr/modern-react-workshop/hooks/node_modules/mdx-deck/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by pomber** [comment] 2019-11-29 14:19
@mxstbr I've just tried with a fresh `npm init code-surfer-deck` and coudn't reproduce your issue (I change the text and it works). 
Do you have more info to reproduce it?

**Comment by mxstbr** [comment] 2019-11-29 14:21
Interesting, let me try to see what's special about my setup. 🤔

**Comment by jebeck** [comment] 2019-11-29 19:15
Strangely, I just got this `Cannot read property 'internal' of null` while I was working, and then remembered I'd seen it pass through my e-mail. In my case it ended up being a JSX that was supposed to be self-closing that I left as `<Component>`. Just thought I'd make a note in case it's useful.

And thanks @trevordmiller for doing that additional testing of the Prettier issue and filing the bug; I got super busy last week and thus unresponsive! I agree it seems to be a Prettier problem.

**Comment by mxstbr** [comment] 2019-11-30 13:16
I figured out what the issue is! When running `yarn start` the initial build completes successfully, however if you change anything the process crashes with the above error.

However, **if you use `npm start` it works perfectly**! Good enough for me 👍

**Comment by pomber** [comment] 2019-11-30 21:49
I can't reproduce it with yarn neither, maybe it's because the template comes with a `package-lock.json` but not a `yarn.lock`.  

Also `gatsby-plugin-mdx` has some problems with the cache and hot reloading (jxnblk/mdx-deck#551), but it's mostly when adding new imports. 

> However, if you use npm start it works perfectly! Good enough for me +1

Glad it works with `npm`, let me know if you have any other problem.

**Comment by gillchristian** [comment] 2019-12-01 11:21
Awesome work! 🎉 

I'm working on some slides [modeling.now.sh](https://modeling.now.sh) ([repo](https://github.com/gillchristian/modeling)). So far the experience is great!

**Closed** 2019-12-10 15:27 UTC

**Comment by aleccool213** [comment] 2019-12-11 15:07
@pomber Hey! Great library! I used v3 recently [for a talk I did last week](https://github.com/aleccool213/apollo-local-state-talk) (repo link). The experience was mostly smooth. 

My only feedback was that it was difficult to find out from the docs how to zoom in on different parts of the same code file.

Thanks!
